### PR TITLE
Argonaut support

### PR DESCRIPTION
**Pull request by bodand**
Argonaut support added with tests and docs for #105.

### CODE REVIEW

**Comment by pauldijou** [comment]
👍 Nice work!

Could you squash all commits into one? Also, could you revert generating the scaladoc? It's super nice to have done it but it makes the pull request really hard to review and it's part of the release process anyway.

Also, I'm off until mid-January so will release at that point (sorry), ping me if I forgot by that point.

**Comment by bodand** [comment]
Squashed them, another two appeared, b/c git. Hopefully reverted the doc generation. Could you check if that worked, and if it did, I'll try to squash these merges as well.

**Comment by bodand** [comment]
Because I still have no idea how the docs work, as I rarely if ever work with sbt.

**Comment by pauldijou** [comment]
Looks like the PR still has 9 commits instead of only one.

Could you remove all new or edited files inside `/docs/src/site`? I will regenerate them.

**Comment by bodand** [comment]
I can't get git && github to work, I've lost control of what's where; let me close this and create a new one with one commit and without messing with the docs. Stay tuned.

**Pull request closed without merging**
