### PR TITLE
Scala Native

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@erwan could you please have a look at this? :pray:

**Comment by sideeffffect** [comment]
@erwan once more, please :pray:

**Comment by sideeffffect** [comment]
@erwan Great, we can merge :tada: Can you also make a release then? :pray:

**Comment by erwan** [comment]
@sideeffffect thank you, I'll take a look!

**Comment by sbrunk** [comment]
I think it makes sense to either wait for https://github.com/jwt-scala/jwt-scala/pull/460 or make the dependency definitions consistent with how it's done there:

https://github.com/jwt-scala/jwt-scala/blob/394f1432fc50afce189b1e94d7fb9dcfb280409b/project/Dependencies.scala#L39-L42

https://github.com/jwt-scala/jwt-scala/blob/394f1432fc50afce189b1e94d7fb9dcfb280409b/build.sbt#L271-L273

**Comment by erwan** [comment]
yes good point, let's progress on the ScalaJS PR before merging this one

**Comment by sideeffffect** [comment]
We can merge it now. Can you also make a release then? :pray:
@erwan

**Comment by sideeffffect** [comment]
@erwan do you think we could get a new release containing this, please? :pleading_face:

**Comment by erwan** [comment]
yes I just released v9.4.0

**Pull request merged**
