### PR TITLE
add support for scala.js

### LINKED ISSUE #258: Scalajs releases?
Any chances this could be published for Scalajs too? 🤔 

Would make my life a lot easier!

### PR DESCRIPTION
**Pull request by massimosiani**
Hi, first of all thanks for the project!

I did my best with the modules I know, I'm not sure if the other modules can be supported as well.
Are you able to publish a snapshot to verify that everything is in place?

Should close #258.

### CODE REVIEW

**Comment by massimosiani** [comment]
Hi, did you have the opportunity to have a look at this?

**Comment by erwan** [comment]
Hi @massimosiani sure, I'll take a look. Thank you for your contribution!

It's a big PR and it's a big investment to decide to maintain the lib for JS as well going forward, so I want to take the time to go through it.

**Comment by erwan** [comment]
You can do a `publishLocal` to publish to your local machine repository to test it

**Comment by massimosiani** [comment]
Hi @erwan, thanks for the reply. Ofc, take your time, I was only wondering if that's a good addition.
If you end up not taking the burden to maintain that (and that's totally understandable from my pov!), I'll look for some way to publish some sort of wrapped version if you don't mind.
If I can convince you, please also consider that AWS Lambda functions are pretty popular, so more and more scala libs are cross compiling to scalajs (and lately to scala native).
Thanks again for the project!

**Comment by 2chilled** [comment]
@erwan @massimosiani Any updates on this? I'm also looking for JWT parser on scalajs, and this lib would be a nice fit.

**Comment by 2chilled** [comment]
:tada: @erwan @massimosiani thank you!

**Comment by erwan** [comment]
hey @massimosiani and @2chilled ,

I published v9.2.0 with the PR merged but I'm not sure the publication of the ScalaJS artifacts was successful. Could you take a look and tell me if it works?

**Comment by xuwei-k** [comment]
- https://github.com/jwt-scala/jwt-scala/issues/451

**Pull request merged**
