### PR TITLE
Play JSON to 2.7.0

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by etspaceman** [comment]
Solves #108

**Comment by pauldijou** [comment]
I wanted to also update Play itself, not just the JSON lib but the tests are now failing because of the global Play not accessible anymore (or whatever).

Does anyone has any experience with ScalaTest and Play and could help me fix those?

**Comment by pauldijou** [comment]
Released in 2.0.0

**Comment by etspaceman** [comment]
You rock! Thanks!

**Comment by pauldijou** [comment]
@prakhunov does, 2.0.0 is mostly its doing 🎉

**Pull request merged**
