### PR TITLE
Add support for spray-json

### LINKED ISSUE #98: Spray-json support
Add [spray-json](https://github.com/spray/spray-json) support.

### PR DESCRIPTION
**Pull request by Slakah**
Closes #98

### CODE REVIEW

**Comment by pauldijou** [comment]
Good job 👍 Will merge next week.

**Comment by Slakah** [comment]
Noticed I didn't add the generated markdown to the samples, should be fixed by https://github.com/pauldijou/jwt-scala/pull/99/commits/d29ae34ccc841920586b4f88e4d1ad05989b4ff6

**Comment by pauldijou** [comment]
Released in 0.19.0

**Comment by Slakah** [comment]
Thanks for the quick turnaround @pauldijou !

**Pull request merged**
