### PR TITLE
Upgrade upickle to 0.8.0

### PR DESCRIPTION
**Pull request by vic**

### CODE REVIEW

**Comment by vic** [comment]
Also upgrades `.travis.yml` to use jdk9 since 8 is now out of service.

**Comment by pauldijou** [comment]
As long as the lib supports Java 8, I think it makes more sense to run the tests on that version.

**Comment by vic** [comment]
@pauldijou the problem is not the upickle library, but travis. since travis has removed jdk 8 and only jdk >= 9 are available on it.

**Comment by pauldijou** [comment]
I see. Still, could you remove it from the PR? Doesn't matter if it fails on Travis, I will fix it on another PR (either using `Trusty` distribution or using `openjdk8`, I want to try to keep testing on Java 8). Thanks for raising the concern, I wasn't really checking all those failures on Travis...

**Comment by vic** [comment]
@pauldijou Done! :)

**Comment by pauldijou** [comment]
Thanks. I will release this Sunday. Ping me if I forget :-)

**Comment by pauldijou** [comment]
Released in 4.2.0

**Pull request merged**
