### PR TITLE
Zio json

### LINKED ISSUE #395: Add support for ZIO-JSON library
Add [ZIO-JSON](https://github.com/zio/zio-json) json library support

### PR DESCRIPTION
**Pull request by dacr**
Add support to zio-json json library - Fix #395

### CODE REVIEW

**Comment by erwan** [comment]
Thank you!

I'm extending your PR to trigger CI and add some doc.

https://github.com/jwt-scala/jwt-scala/pull/396

**Comment by erwan** [comment]
I have activated CI in a different branch and fixed a few issues, could you create some doc in the following directory?

https://github.com/jwt-scala/jwt-scala/tree/master/docs/src/main/mdoc

Documentation to test your doc locally is here: https://github.com/jwt-scala/jwt-scala/blob/master/CONTRIBUTING.md

**Comment by dacr** [comment]
ok I'll do it in a few days, thanks for the links

**Comment by dacr** [comment]
#398 fixed

**Comment by erwan** [comment]
thank you!

**Pull request merged**
