### PR TITLE
Update circe to 0.13.0

### PR DESCRIPTION
**Pull request by howyp**

### CODE REVIEW

**Comment by howyp** [comment]
Thanks @pauldijou. Any idea when you might be able to get a new release out, please?

**Comment by pauldijou** [comment]
By the end of the month. I will try to find time before but no guarantee.

**Comment by pauldijou** [comment]
Thanks for your patience, finally found some time this weekend. Released in 4.3.0

**Comment by howyp** [comment]
Thanks for sorting it @pauldijou 👍

**Pull request merged**
