### PR TITLE
Play JSON to 2.7.1

### PR DESCRIPTION
**Pull request by etspaceman**
2.7.0 is bugged

### CODE REVIEW

**Comment by etspaceman** [comment]
See https://github.com/playframework/play-json/commit/7b9da5a4cf06b7578be47956b36513a0c99be492

**Comment by pauldijou** [comment]
Seriously? :-( I'm away and won't be able to release anything for about a week. Will do as soon as I come back (please ping me if I forgot)

**Comment by maccamlc86400** [comment]
Yes. I have run into this problem today.

If it can be merged and released asap that would be brilliant

**Comment by maccamlc86400** [comment]
Appears to be a binary compatibility issue with Reads. Scala Collection Compat was removed in 2.7.1. But as this library compiled against 2.7.0 I am getting NoClassDefFound errors

**Comment by maccamlc86400** [comment]
```
[ERROR] [2019-02-21T15:58:23.692+1100] [error] i.e.r.ErrorResponse - Unhandled exception : java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
java.lang.RuntimeException: java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
	at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:425)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
Caused by: java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
	at pdi.jwt.JwtJsonImplicits.pdi$jwt$JwtJsonImplicits$$extractStringSetOrString(JwtJsonImplicits.scala:14)
	at pdi.jwt.JwtJsonImplicits$$anon$3.reads(JwtJsonImplicits.scala:38)
	at pdi.jwt.JwtJson$.parseClaim(JwtJson.scala:27)
```

Play 2.7.0 has Play-Json 2.7.1 and to my understanding, causes the above stack trace

**Comment by etspaceman** [comment]
Hey Paul -

You around to merge / deploy this?

**Comment by pauldijou** [comment]
I will be back in the evening, will try do it during the weekend.

**Comment by pauldijou** [comment]
Released in 2.1.0

**Pull request merged**
